### PR TITLE
Regrading bug fixed (and other assorted changes)

### LINKED ISSUE #95: BUG/REGRESSION - answers disappear after regrading
qtype_matrix version: https://github.com/ndunand/moodle-qtype_matrix/releases/tag/2025093000
moodle version: 4.5.7 (Build: 20251006)

In the recent version 2025093000 of qtype_matrix a severe bug occurs: As soon as a teacher edits a question of a quiz with attempts and regrades the quiz all of the answers of students are empty and thus marked as incorrect.

### Steps to reproduce the bug:
1. Create a qtype_matrix question with at least one item. The correct answer can be set to True.
2. In the quiz settings enable all review options (to see the feedback later on as a student)
3. As a student take the quiz. E.g. answer False to get 0 points.
4. As a student open the review: You see the appropriate feedback (answer chosen and points).
5. As a teacher change the question. Flip the item's answer from False to True to change the question and create a new version.
6. Regrade the quiz
7. As a student: open the quiz review

### Expected behaviour
After regrading the student sees the quiz review according to the new rules of the question. The student can see points awarded and the own answer.

### Ocurring bug
After grading the student/teacher sees no answers of the student. The student is given 0 points as if there was never an answer given.

### PR DESCRIPTION
**Pull request by danowar2k**
This fixes #95. It's not yet done because it's still a gigantic commit and I will try to split it up into several ones.

### CODE REVIEW

**Comment by danowar2k** [comment]
I've opened it because it will take some time to split up and you can already look at the code.

**Comment by danowar2k** [comment]
Found a few things I'll edit in:

- upgrade save point is missing
- param_add_rows() can be removed
- disabled_if() function can be removed

EDIT: Rebased/squashed.

**Comment by danowar2k** [comment]
Had found a "bug": The new code also saved stepdata when you responded with false/not checked/"0". As this leads to severe table data bloat, I fixed that.

(Also I would have to change more code to accomodate for the "0" entries, so good that I quickly found how to prevent it)

EDIT: Tests didn't detect the bug because the answers I generate for the tests are "sparse" (don't contain 0 values). The tested functions thus worked. But the real data stored "0" entries.

Your tests are only as good as the accuracy of your simulated test data  ;-)

**Comment by danowar2k** [comment]
Sigh...the bug is still present, even if I let unselected cells have an empty value. So, still looking for a solution...

**Comment by danowar2k** [comment]
Finally the bug is gone. Side effect: I now know where responses / values for step data storage are extracted from submitted data (POST) and why PARAM_BOOL alone did not help (Empty string casted to false, false is casted to "0" when storing the stepdata value). 

Now I use hidden checkboxes instead of just hidden inputs because using those parameter/value combos will just not get sent when they are not checked.

File: classes/db/stepdata_migration_utils.php [hunk 1]
```diff
@@ -0,0 +1,197 @@
...
+            }
+            $matrix['cols'][] = $matrixcol->colid;
+            if (!isset($matrix['attemptroworder'])) {
+                $matrix['attemptroworder'] = [];
+            }
+        }
+        unset($matrixcols);
+
+        // Collect info about attempt row order.
+        $orderstepdatasql = stepdata_migration_utils::stepdata_sql($qinsql, '^_order$');
```
Comment (ndunand) [inline classes/db/stepdata_migration_utils.php]: @danowar2k This translates into 

```sql
[...] AND qasd.name ~ '^_order$' ORDER BY qasd.name [...]
```

and yields the following 

```
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '~ '^_order$' ORDER BY qasd.name DESC, [...]
```

Is this regex really necessary? `~ '^_order$'` is equivalent to ` = '_order'`, no ?

Comment (ndunand) [reply classes/db/stepdata_migration_utils.php]: changed this to `'_order'` (and to `'cell%'` below on line #L141 does fix the upgrade step for me. Of course the 1st one is not really a LIKE anymore but it avoids having to modify the `stepdata_sql()` function.

**Comment by ndunand** [comment]
CLI update step, tested on production database copy.

After an initial scare (4.2% after 11 minutes), the attempt steps data upgrade step finished after 17 minutes (23985 questions and about 1M attrmpt_step_data rows Matrix)

File: classes/db/stepdata_migration_utils.php (hunk 1 above)
Comment (danowar2k) [reply classes/db/stepdata_migration_utils.php]: I forgot that ~ is a Postgres only command. I'll rework that into either a LIKE for everything or maybe into something where I use ~ only if the database is a postgres one.

Comment (ndunand) [reply classes/db/stepdata_migration_utils.php]: Just changed this to 
```diff
diff --git a/classes/db/stepdata_migration_utils.php b/classes/db/stepdata_migration_utils.php
index 9cc7dea..21a8dcd 100644
--- a/classes/db/stepdata_migration_utils.php
+++ b/classes/db/stepdata_migration_utils.php
@@ -77,7 +77,7 @@ class stepdata_migration_utils {
                 JOIN {question_attempt_steps} qas ON qas.questionattemptid = qa.id
                 JOIN {question_attempt_step_data} qasd ON qasd.attemptstepid = qas.id
                 WHERE q.id ".$qinsql. "
-                AND qasd.name ~ '".$stepdatanameregex."' ORDER BY qasd.name DESC, q.id ASC, qa.id ASC, qas.id ASC, qasd.id ASC 
+                AND qasd.name LIKE '".$stepdatanameregex."' ORDER BY qasd.name DESC, q.id ASC, qa.id ASC, qas.id ASC, qasd.id ASC 
             ";
     }
 
@@ -122,7 +122,7 @@ class stepdata_migration_utils {
         unset($matrixcols);
 
         // Collect info about attempt row order.
-        $orderstepdatasql = stepdata_migration_utils::stepdata_sql($qinsql, '^_order$');
+        $orderstepdatasql = stepdata_migration_utils::stepdata_sql($qinsql, '_order');
         $orderdatarecords = $DB->get_records_sql($orderstepdatasql, $qidparams);
         foreach ($orderdatarecords as $orderdata) {
             if (!isset($matrixinfos[$orderdata->questionid])) {
@@ -138,7 +138,7 @@ class stepdata_migration_utils {
     public static function migrate_stepdata(array $matrixinfos, array $questionids):void {
         global $DB;
         [$qinsql, $qidparams] = $DB->get_in_or_equal(array_keys($questionids));
-        $cellstepdatasql = self::stepdata_sql($qinsql, '^cell');
+        $cellstepdatasql = self::stepdata_sql($qinsql, 'cell%');
         $celldatarecords = $DB->get_records_sql($cellstepdatasql, $qidparams);
         $nrcelldata = count($celldatarecords);
         $celldatacount = 0;
```
and it worked.

**Comment by ndunand** [comment]
What about 40df54d and 57f8771 ? These seem to be more recent commits that are replacing 09d16e6 and 1cac831 ?

Edit: @danowar2k wondering because I've started testing and pulled before those two.

**Comment by danowar2k** [comment]
> What about [40df54d](https://github.com/ndunand/moodle-qtype_matrix/commit/40df54d829e3095a71ce3dca4198206c5d199f24) and [57f8771](https://github.com/ndunand/moodle-qtype_matrix/commit/57f877109bc572a80ed8067c443121a60e9a4d33) ? These seem to be more recent commits that are replacing [09d16e6](https://github.com/ndunand/moodle-qtype_matrix/commit/09d16e618b878bc20eff7e7c18d70cff1eae2a0d) and [1cac831](https://github.com/ndunand/moodle-qtype_matrix/commit/1cac83195dd15fbe26d20cecb07f20dbdaecf0a0) ?
> 
> Edit: @danowar2k wondering because I've started testing and pulled before those two.

The first of those just replaces the old commit by doing a LIKE instead of ~ to be database agnostic, just like you asked. Currently testing the like variant locally. Results when using ~ and LIKE:

```
-- Exam Moodle Staging, localhost database
-- Specs: 4GB RAM, 4 Cores
-- "1. questions: 47798"
-- "2. matrix questions: 7562"
-- "3. options: 7562"
-- "4. cols: 5887"
-- "5. all attempt step data: 3884150"
-- "6. order data: 428136"
-- "7. cell data: 1371413"
-- Time for upgrade from 02 to 04 (with ~): 272 seconds
-- Time for upgrade from 02 to 04 (with LIKE): 269,80 seconds
```

So basically I won't do a platform specific query :-D

EDIT: The second commit isn't changed, just git's specific way to change the hash when the parent commit has changed.

**Comment by danowar2k** [comment]
Just found the compare link that Github generates so that you can see what I've done between the old and the force pushed commits: https://github.com/ndunand/moodle-qtype_matrix/compare/1cac83195dd15fbe26d20cecb07f20dbdaecf0a0..57f877109bc572a80ed8067c443121a60e9a4d33

image

There it is, not very prominent at the end of the line (and not even a button or explicit looking link...)

**Comment by danowar2k** [comment]
What's the status here? I'm asking because I'm currently in the process of getting sick and have the next two weeks off caused by overtime...

**Comment by danowar2k** [comment]
Huh, I just saw another possible optimization in the UPDATE query. I do SET value = CASE WHEN there all the time, but I really don't have to because I always set value to '1' and limit the updated records with the IN() clause. I'll test this and update the PR.

**Comment by danowar2k** [comment]
Local testing showed the UPDATE query to go from 3 minutes to 5 seconds for a table containing 53 million records (our teaching production)

**Comment by ndunand** [comment]
Hi, from my testing on a clone of our production system everything looks fine. Old attempts as well as regarding seems to work without issue.

**Comment by danowar2k** [comment]
I just had a too much memory bug when testing with 53 million records. Back to the drawing board...

**Comment by danowar2k** [comment]
Okay, I think I've fixed the bug that happens when working with huge recordsets. This will probably change performance again because I'm doing 10000 record batches, so I am upping the nr of requests. I don't know whether I could do bigger batches but first I'll test this with my teaching data copy.

**Comment by danowar2k** [comment]
Sigh, with this changes the update would still be running now if I started it yesterday. 

I'll tweak the code...

**Comment by danowar2k** [comment]
Okay, I've changed to recordsets, and tested it on teaching system data (53 Million stepdata records) and the result was 108 minutes runtime.
Currently looking for missed records. Will then test again on exam data.

**Comment by danowar2k** [comment]
If you're going to merge it, I'd like to rebase it before that so it would be less messy commits.

**Comment by ndunand** [comment]
Yes, I'll be going to merge soon. I want to test once more the upgrade step on a copy of the production database, as well as the other fixes. Should I test with the current code?

**Comment by danowar2k** [comment]
Currently sick here, but needed to finish this so you can merge if you want and my colleagues can go on, too.
Rebased/Squashed the newer commits into the "main change" commit.
Tested it on teaching and exam Moodle.
exam now: 

```
-- Exam Moodle Staging, localhost database
-- Specs: 4GB RAM, 4 Cores
-- "1. questions: 47798"
-- "2. matrix questions: 7562"
-- "3. options: 7562"
-- "4. cols: 5887"
-- "5. all attempt step data: 3884150"
-- "6. order data: 428136"
-- "7. cell data: 1371413"
-- Time for upgrade from 02 to 04: 146 seconds
```

So going to recordsets helped with the performance.

```
Teaching Moodle Staging, remote database
Specs Moodle: 4GB RAM, 2 Cores
Specs Postgres Database: 10GB RAM, 4 Cores
"1. questions: 362632"
"2. matrix questions: 48815"
"7. cell data: 300954"
"4. cols: 72099"
"6. order data: 5782363"
"5. all attempt step data: 53311625"
"3. options: 48815"
Time for upgrade from 02 to 04: 108 minutes
```

We added a tag to our fork and will use it to update.

**Comment by ndunand** [comment]
Hope you're getting better.

Tested again on production clone and upgrade step works fine.

A side effect I have noticed that seems to be linked to the change in QASD format: restoring a backup from a site running an older qtype_matrix version (for instance had I done the upgrade in production and wanted to pick a course backup to restore) to a site running this branch of qtype_matrix yields the following error.
(I had to turn off `enableasyncbackup` for this to show, as a background backup would only stall at 0% without any indication.

```
Warning: Undefined array key "_order" in /var/....../question/type/matrix/backup/moodle2/restore_qtype_matrix_plugin.class.php on line 207
error/error_qtype_matrix_attempt_step_data_not_migratable

[More information about this error](https://docs.moodle.org/500/en/error/moodle/error_qtype_matrix_attempt_step_data_not_migratable)

Debug info:
Error code: error_qtype_matrix_attempt_step_data_not_migratable
$a contents: Dismiss this notification
Stack trace:
line 210 of /question/type/matrix/backup/moodle2/restore_qtype_matrix_plugin.class.php: restore_step_exception thrown
line 6291 of /backup/moodle2/restore_stepslib.php: call to restore_qtype_matrix_plugin->recode_response()
line 6266 of /backup/moodle2/restore_stepslib.php: call to restore_questions_activity_structure_step->questions_recode_response_data()
line 6160 of /backup/moodle2/restore_stepslib.php: call to restore_questions_activity_structure_step->restore_question_attempt_step_worker()
line 137 of /backup/util/plan/restore_structure_step.class.php: call to restore_questions_activity_structure_step->process_question_attempt_step()
line 123 of /backup/util/helper/restore_structure_parser_processor.class.php: call to restore_structure_step->process()
line 150 of /backup/util/xml/parser/processors/grouped_parser_processor.class.php: call to restore_structure_parser_processor->dispatch_chunk()
line 206 of /backup/util/xml/parser/progressive_parser.class.php: call to grouped_parser_processor->after_path()
line 286 of /backup/util/xml/parser/progressive_parser.class.php: call to progressive_parser->inform_end()
line ? of unknownfile: call to progressive_parser->end_tag()
line 177 of /backup/util/xml/parser/progressive_parser.class.php: call to xml_parse()
line 156 of /backup/util/xml/parser/progressive_parser.class.php: call to progressive_parser->parse()
line 110 of /backup/util/plan/restore_structure_step.class.php: call to progressive_parser->process()
line 199 of /backup/util/plan/base_task.class.php: call to restore_structure_step->execute()
line 233 of /backup/moodle2/restore_activity_task.class.php: call to base_task->execute()
line 191 of /backup/util/plan/base_plan.class.php: call to restore_activity_task->execute()
line 168 of /backup/util/plan/restore_plan.class.php: call to base_plan->execute()
line 411 of /backup/controller/restore_controller.class.php: call to restore_plan->execute()
line 219 of /backup/util/ui/restore_ui.class.php: call to restore_controller->execute_plan()
line 146 of /backup/restore.php: call to restore_ui->execute()
```

Let me know if you'd rather have me open an issue for this.

**Comment by danowar2k** [comment]
Yeah, please open a new issue. Looks like I did too many assumptions when testing the restore and not enough xdebugging.

Basically, I assumed that the response passed to the function is an amalgam of all step data for the attempt. Which, thinking about it, is stupid to assume. Of course, restore processes one step's data after another.
So the problem is, the first "response" for an attempt only contains _order. So you recode the order and return.
Then the second (and later) "response" data do not contain _order anymore, but only the cell/row data.
So you basically have to do the function this way:

- If there is _order, recode that and return
- If there is cell data, fetch the already stored new _order data (or maybe do a kind of caching in the class to prevent that?) to have that at hand, and recode the cell data to row data
- If there is row data, don't do anything because it uses indices and doesn't need to be changed.

**Comment by danowar2k** [comment]
Restore is fixed.

**Comment by ndunand** [comment]
Thanks. It takes me many hours every time to re-check the full upgrade on my production clone, and the rest of the checks. I think this is really ready for merge now.
